[www]
pm = dynamic
pm.max_children = 40
pm.start_servers = 10
pm.min_spare_servers = 8
pm.max_spare_servers = 20
pm.max_requests = 1000
listen.backlog = 2048
request_terminate_timeout = 900s
catch_workers_output = yes
decorate_workers_output = no
